# .github/workflows/publish-docker-image.yml

# Name of the workflow, which will be displayed in the "Actions" tab of your repo
name: Build and Publish Docker Image

# --- Trigger ---
# This workflow runs on every push to the 'main' branch
on:
  push:
    branches:
      - main

# --- Jobs ---
# Defines the sequence of tasks to be executed
jobs:
  build-and-push:
    # The type of virtual machine to run the job on. 'ubuntu-latest' is standard.
    runs-on: ubuntu-latest

    # A sequence of steps that make up the job
    steps:
      # Step 1: Check out the repository code
      # This action downloads your source code into the runner.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      # Uses the secrets we created earlier to authenticate.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push the Docker image
      # This is the core step. It uses the Dockerfile to build the image
      # and then pushes it to your Docker Hub repository.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/earth-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/earth-backend:${{ github.sha }}