# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.35
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/23287315005
# Commit: https://github.com/zenopie/earth-network-backend/commit/863668de14bdd92ffe9edb27f5a031ef177c04d5
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:5de672e79c83b5c88d1dd8d49b784a950b644fd7e591fe2c53f2696c0b66ca59
    ports:
      - '8000'
