# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.47
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/32959623019
# Commit: https://github.com/zenopie/earth-network-backend/commit/7c5caef7c747d409ace55ab2a1d99f9e17218718
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:3e1ea8093a2005fb7e549fd860e878d7374797ba20ea8da08a0892825f160ef3
    ports:
      - '8000'
