services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:delegated
    restart: unless-stopped
