# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.46
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/32096311647
# Commit: https://github.com/zenopie/earth-network-backend/commit/7d734792f00a965583ac3b51cbb4ea32720e861e
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:ecb26e2536864f12a745f7e88edd0ce1e77c0b2d82c614bd231efa1df25cc206
    ports:
      - '8000'
